.TH AUTO-ADMIN 8

.SH NAME
auto-admin - Portable, command-line systems management scripts

.SH SYNOPSIS
.PP
.nf 
.na
auto-admin
.ad
.fi

.SH ARGUMENTS
.nf
.na
None
.ad
.fi

.SH DESCRIPTION

auto-admin provides the main menu for common auto-admin tasks such as
updating the system, managing users, services, etc.

auto-admin - Portable, command-line systems management scripts
.ad
.fi

.SH "SEE ALSO"
stdio(3)

.SH AUTHOR
.nf
.na
J Bacon
