#!/bin/sh

if [ $# != 1 ]; then
    cat << EOM
Usage: $0 S1|S2|S3|S4|S5|NONE
Run "man acpi" for more information.
EOM
    exit 1
fi

# Enable suspend on lid-close
# hw.acpi.lid_switch_state exists whether or not computer has a lid
if ! sysctl hw.acpi.supported_sleep_state | fgrep -q $1; then
    printf "$1 is not a supported state.\n"
    exit 1
fi

# FIXME: Not a clean removal - may leave comments from append-line
fgrep -v lid_switch_state /etc/sysctl.conf > /etc/sysctl.conf.desktop-installer
mv -f /etc/sysctl.conf.desktop-installer /etc/sysctl.conf
auto-append-line lid_switch_state "hw.acpi.lid_switch_state=$1" \
    /etc/sysctl.conf desktop-installer
sysctl hw.acpi.lid_switch_state=$1

