#!/bin/csh

##########################################################################
#   Description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2012-01-08  Jason Bacon Begin
##########################################################################

switch(`uname`)
case    FreeBSD:
    set before=`df -m /usr | awk '$6 == "/usr" { print $4 }'`
    printf "Initial free space: %d\n" $before
    cd /usr/ports
    rm -rf distfiles/*
    foreach dir ( `ls -d */*/work`)
	# Make sure it still exists - may have been wiped by a recursive clean
	if ( -e $dir ) then
	    echo "Cleaning $dir..."
	    cd $dir/..
	    make clean
	    cd /usr/ports
	endif
    end
    set after=`df -m /usr | awk '$6 == "/usr" { print $4 }'`
    printf "Initial free space: %d\n" $before
    printf "Final free space: %d\n" $after
    @ diff = $after - $before
    printf "%d megabytes freed.\n" $diff
    breaksw
case    Darwin:
    port clean --all installed
    breaksw
default:
    echo "OS `uname` is not supported by $0."
    exit 1
endsw

