#!/bin/sh

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2012-01-08  Jason Bacon Begin
##########################################################################


install_from_port()
{
    PACKAGEROOT=
    PACKAGESITE=
    export PACKAGEROOT PACKAGESITE
    (cd /usr/ports/$port && make -DBATCH install)
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    printf "Usage: $0 [-l] category/port [category/port ...]\n"
    exit 1
fi

if [ $1 = '-l' ]; then
    literal_package_name=1
    shift
else
    literal_package_name=0
fi

# FIXME: Allow override
PORTSDIR='/usr/ports'

# Allow mirrors to be used without having PACKAGEROOT set globally.
if [ x$AUTO_BUILD_FROM_SOURCE != xyes ] && [ x$AUTO_PACKAGEROOT != x ]; then
    export PACKAGEROOT=$AUTO_PACKAGEROOT
else
    export PACKAGEROOT="ftp://ftp.freebsd.org"
fi

# Use -stable instead of -release for release candidates
if uname -r | fgrep -q RELEASE; then
    # Keep whole version and remove -RELEASE
    release=$(uname -r | cut -d '-' -f 1)'-release'
else
    # Keep only major version
    release=$(uname -r | cut -d '.' -f 1)'-stable'
fi

if [ $literal_package_name = 1 ]; then
    release=$release/Latest
else
    release=$release/All
fi

PACKAGEDIR=$(uname -p)'/packages-'$release
PACKAGESITE=$PACKAGEROOT/pub/FreeBSD/ports/$PACKAGEDIR/
export PACKAGESITE

for port in $*; do
    # Make sure each is given as category/port
    if ! printf $port | fgrep -q '/'; then
	printf "${0}: $port missing category.\n"
	exit 1
    fi
    
    if [ ! -d ${PORTSDIR}/$port ]; then
	printf "$port does not exist.\n"
	break
    fi
    
    # Deducing the generic (non-versioned) package name is difficult
    # such as in eigen vs eigen2 and net/jags vs math/jags.
    if [ $literal_package_name = 1 ]; then
	pkg_name=`basename $port`
    else
	pkg_name=`auto-print-make-variable $port PKGNAME`
    fi
    if ! auto-package-installed $port; then
	if [ x$AUTO_BUILD_FROM_SOURCE = xyes ]; then
	    install_from_port
	    status=$?
	else
	    tries=2
	    # Short: pub/FreeBSD/ports/amd64/packages-8.3-release/Latest
	    # Versioned: pub/FreeBSD/ports/amd64/packages-8.3-release/All
	    if [ $literal_package_name != 1 ]; then
		
	    fi
	    if [ -e /media/packages/All/$pkg_name.tbz ]; then
		pkg_flags=''
		pkg_name="/media/packages/Latest/$pkg_name.tbz"
		printf 'Installing from CD/DVD...\n'
	    else
		pkg_flags='-Fr'
		printf 'Installing from network...\n'
	    fi
	    while ! pkg_add $pkg_flags $pkg_name && [ $tries -gt 0 ]; do
		printf "Error installing $port.  $tries more tries.\n"
		tries=$((tries-1))
	    done
	    if [ $tries -gt 0 ]; then
		status=0
	    else
		if [ x$AUTO_BUILD_FROM_SOURCE = xfall-back ]; then
		    printf "Giving up on binary package.  Attempting to build from source...\n"
		    install_from_port
		    status=$?
		else
		    # Better status value (from pkg_add?)
		    status=1
		fi
	    fi
	fi
    fi
done
exit $status

