#!/bin/sh

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-01-21  Jason Bacon Begin
##########################################################################

##########################################################################
#   Function description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-01-21  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 category/port variable-name\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

#
case $# in
2)
    ports_dir='/usr/ports'
    ;;
4)
    if [ $1 = '-p' ]; then
	ports_dir=$2
	shift
	shift
    else
	usage
    fi
    ;;
*)
    usage
    ;;
esac

if [ ! -d $ports_dir/$1 ]; then
    printf "No such port: $ports_dir/$1\n"
    exit 2
fi

makefile=/tmp/pkgname.$$
cat << EOM > $makefile
print-variable:
	@echo \${$2}

.include "$ports_dir/$1/Makefile"
EOM

# cat $makefile
cd $ports_dir/$1
make -f $makefile print-variable
rm -f $makefile

