#!/bin/sh -e

if [ $# = 1 ]; then
    user_name=$1
else
    user_name=''
fi

while [ 0$user_name = 0 ]; do
    printf "Username? "
    read user_name
done

if [ -e /usr/local/etc/ldap.conf ]; then
    # Flag usernames not in LDAP
    ldap_verified_uid=`ldapsearch uid=$user_name | awk '$1 == "uid:" { print $2 }'`
    if [ 0$ldap_verified_uid != 0$user_name ]; then
	printf "User $user_name is not in the LDAP directory.  Continue? (y/n) "
	read resp
	if [ 0$resp != 0'y' ]; then
	    exit 0
	fi
    fi
fi

printf "Primary group? [default=$user_name] "
read primary_group
if [ 0$primary_group = 0 ]; then
    primary_group=$user_name
fi

printf "Other groups (separated by commas)? "
read othergroups

default_comment=`ldapsearch uid=$user_name | awk '$1 == "cn:" { for (c=2; c<NF; ++c) printf("%s ", $c); printf("%s", $NF); }'`
comment=''
while [ 0"$comment" = 0 ]; do
    printf "Comment? [default = '$default_comment'] "
    read comment
    if [ 0"$comment" = 0'' ]; then
	comment=$default_comment
    fi
done

printf "User ID? [Press return for default] "
read user_id

default_shell="/usr/local/bin/bash"
cat /etc/shells
printf "\nShell? [$default_shell] "
read shell
if [ 0$shell = 0 ]; then
    shell=$default_shell
fi

groupadd_cmd="pw groupadd $primary_group"
if [ 0$user_id != 0 ]; then
    groupadd_cmd="$groupadd_cmd -g $user_id"
fi

# Order of pw flags matters!
useradd_cmd="pw useradd $user_name -w random"
if [ 0$user_id != 0 ]; then
    useradd_cmd="$useradd_cmd -u $user_id"
fi
useradd_cmd="$useradd_cmd -c '$comment' -g $primary_group"
if [ 0$othergroups != 0 ]; then
    useradd_cmd="$useradd_cmd -G \"$othergroups\""
fi
useradd_cmd="$useradd_cmd -m -s $shell"

# Eval here to expand before running
printf "$groupadd_cmd\n"
eval $groupadd_cmd
printf "$useradd_cmd\n"
eval $useradd_cmd
if [ 0$user_name = 0$ldap_verified_uid ]; then
cat << EOM

This user can authenticate using either LDAP or the temporary password
shown above.  It is therefore optional to provide this temporary password
to the user.

EOM
else
cat << EOM

Record the temporary password shown above.  This is the only means by which
this user can authenticate.

EOM
fi

