#!/bin/sh

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2012-01-08  Jason Bacon Begin
##########################################################################

##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    printf "Usage: $0 [-p] category/port [category/port ...]\n"
    exit 1
fi

if [ $1 = '-p' ]; then
    literal_package_name=1
    shift
else
    literal_package_name=0
fi

# FIXME: Allow override
PORTSDIR='/usr/ports'

# Allow mirrors to be used without having PACKAGEROOT set globally.
if [ x$AUTO_BUILD_FROM_SOURCE != xyes ] && [ x$AUTO_PACKAGEROOT != x ]; then
    export PACKAGEROOT=$AUTO_PACKAGEROOT

    # Auto-correct PACKAGESITE to use -stable instead of -release for release
    # candidates
    if ! uname -r | fgrep -q RELEASE; then
	PACKAGESITE=$PACKAGEROOT'/pub/FreeBSD/ports/i386/packages-'$(uname -r | cut -d '.' -f 1)'-stable/Latest/'
	export PACKAGESITE
    fi
fi

for port in $*; do
    # Make sure each is given as category/port
    if ! printf $port | fgrep -q '/'; then
	printf "${0}: $port missing category.\n"
	exit 1
    fi
    
    if [ ! -d ${PORTSDIR}/$port ]; then
	printf "$port does not exist.\n"
	break
    fi
    
    # Deducing the generic (non-versioned) package name is difficult
    # such as in eigen vs eigen2 and net/jags vs math/jags.
    if [ $literal_package_name = 1 ]; then
	pkg_name=`basename $port`
    else
	pkg_name=`auto-print-make-variable $port PKGNAME`
    fi
    if ! auto-package-installed $port; then
	if [ x$AUTO_BUILD_FROM_SOURCE = xyes ]; then
	    PACKAGEROOT=
	    PACKAGESITE=
	    export PACKAGEROOT PACKAGESITE
	    (cd /usr/ports/$port && make -DBATCH install)
	    status=$?
	else
	    tries=2
	    # FIXME: Try both port name (e.g. eigen2 vs eigen) and
	    # package name (e.g. clp vs Clp)
	    while ! pkg_add -Fr $pkg_name && [ $tries -gt 0 ]; do
		printf "Error installing $port.  $tries more tries.\n"
		tries=$((tries-1))
	    done
	    if [ $tries -gt 0 ]; then
		status=0
	    else
		if [ x$AUTO_BUILD_FROM_SOURCE = xfall-back ]; then
		    printf "Giving up on binary package.  Attempting to build from source...\n"
		    PACKAGEROOT=
		    PACKAGESITE=
		    export PACKAGEROOT PACKAGESITE
		    (cd /usr/ports/$port && make -DBATCH install)
		    status=$?
		else
		    # Better status value (from pkg_add?)
		    status=1
		fi
	    fi
	fi
    fi
done
exit $status

