#!/bin/sh -e

case `uname` in
    FreeBSD)
	os='FreeBSD'

	if [ -s $PREFIX ]; then
	    PREFIX=/usr/local/auto-admin
	fi
	;;
    Linux)
	#
	if [ -e /etc/redhat-release ]; then
	    os='CentOS'
	else
	    printf "Only RHEL-based Linux is supported.\n"
	    exit 1
	fi

	if [ -s $PREFIX ]; then
	    PREFIX=/usr/local
	fi
	DATADIR=$PREFIX/share/auto-admin
	mkdir -p $DATADIR
	;;
    *)
	printf "Unsupported OS: `uname`\n"
	exit 1
esac

set -x
rm -f ${STAGEDIR}${PREFIX}/sbin/auto-*
cp Scripts/* ${STAGEDIR}${PREFIX}/sbin
chmod 750 ${STAGEDIR}${PREFIX}/sbin/*
