#!/bin/sh

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2012-01-08  Jason Bacon Begin
#   2012-10-10  Jason Bacon Adapted from FreeBSD to pkgsrc
##########################################################################

##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    printf "Usage: $0 category/port [category/port ...]\n"
    exit 1
fi

SOURCE_PREFIX=/usr/pkgsrc

# Set PKG_PATH
. /usr/pkgsrc.shrc

for pkg in $*; do
    # Make sure each package is given as category/port
    if ! printf $pkg | fgrep -q '/'; then
	printf "${0}: $pkg missing category.\n"
	exit 1
    fi
    
    if ! auto-package-installed $pkg; then
	if [ x$AUTO_BUILD_FROM_SOURCE = xyes ]; then
	    (cd ${SOURCE_PREFIX}/$pkg && make -DBATCH install)
	    status=$?
	else
	    tries=2
	    while ! pkg_add `basename $pkg` && [ $tries -gt 0 ]; do
		printf "Error installing $pkg.  $tries more tries.\n"
		tries=$((tries-1))
	    done
	    if [ $tries -gt 0 ]; then
		status=0
	    else
		if [ x$AUTO_BUILD_FROM_SOURCE = xfall-back ]; then
		    printf "Trying to build from source...\n"
		    auto-install-packages-from-source $pkg
		    status=$?
		fi
	    fi
	fi
    fi
done
exit $status

