#!/bin/sh -e

##########################################################################
#   Script description:
#       Print the PREFIX of the pkgsrc installation currently in path.
#       
#   History:
#   Date        Name        Modification
#   2018?       Jason Bacon Begin
##########################################################################

printf "/usr/pkg\n"
