#!/bin/sh -e

##########################################################################
#   Script description:
#       Print the PREFIX of the pkgsrc installation currently in path.
#       
#   History:
#   Date        Name        Modification
#   2018?       Jason Bacon Begin
##########################################################################

prefix="/usr/pkg"

if [ -e $prefix ]; then
    printf "$prefix\n"
fi
