#!/bin/sh -e

cd $(auto-pkgsrc-dir)

printf "Github username? [none] "
read username
if [ 0$username = 0 ]; then
    git clone https://github.com/outpaddling/dreckly-wip.git
else
    git clone https://$username@github.com/outpaddling/dreckly-wip.git
fi
cd wip
git config pull.rebase true

printf "\nEditing .gitconfig.\n\n"

printf "Full name? "
read name

printf "Email? "
read email

printf "Editor? [vi] "
read editor
if [ 0$editor = 0 ]; then
    editor=vi
fi
git config --global user.name "$name"
git config --global user.email $email
git config --global core.editor $editor
more ~/.gitconfig
