#!/bin/sh -e

##########################################################################
#   Script description:
#       Print the path of the pkgsrc source tree for the currently active
#       pkgsrc installation.
#       
#   History:
#   Date        Name        Modification
#   2018?       Jason Bacon Begin
##########################################################################

if [ -n "$PKGSRCDIR" ]; then
    printf "$PKGSRCDIR\n"
else
    dir="/usr/pkgsrc"
    if [ -e $dir ]; then
	printf "$dir\n"
    fi
fi
