#!/bin/sh

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2012-10-10  Jason Bacon Begin
##########################################################################

##########################################################################
#   Main
##########################################################################

# FIXME: Determine the latest automatically

unset PKG_PATH
year=`date +%Y`
for Q in ${year}Q4 ${year}Q3 ${year}Q2 ${year}Q1; do
    printf "Checking for $Q...\n"
    if fetch -q http://ftp.NetBSD.org/pub/pkgsrc/packages/$(uname -s)/$(uname -m)/$(uname -r|cut -f '1 2' -d.)_${Q}/SHA512.bz2 2> /dev/null; then
	PKG_PATH="http://ftp.NetBSD.org/pub/pkgsrc/packages/$(uname -s)/$(uname -m)/$(uname -r|cut -f '1 2' -d.)_${Q}/All"
	rm SHA512.bz2
	printf "Using $Q.\n"
	break
    fi
done

if [ x$PKG_PATH = x ]; then
    printf "Could not find a quarterly snapshot!\n"
    exit 1
fi
exit

# FIXME: Don't assume /usr
# Create env scripts
cat << EOM > /usr/pkgsrc.shrc
PKG_PATH=$PKG_PATH
export PKG_PATH
PKGSRC_QUARTER=$Q
export PKGSRC_QUARTER
EOM

cat << EOM > /usr/pkgsrc.cshrc
setenv PKG_PATH $PKG_PATH
setenv PKGSRC_QUARTER $Q
EOM

echo $PKG_PATH

