#!/bin/sh -e

##########################################################################
#   Script description:
#       Fetch install media matching this installation
#
#   Arguments:
#       Install media format (bootonly, disc1, dvd1, memstick, mini-memstick)
#       
#   History:
#   Date        Name        Modification
#   2019-06-15  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 bootonly|disc1|dvd1|memstick|mini-memstick\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi
format=$1

case $(auto-ostype) in
FreeBSD)
    site=$(auto-fastest-mirror)
    image=$(auto-install-media-distname $format)
    release=$(uname -r | awk -F - '{ print $1 }')
    url=$site/pub/FreeBSD/releases/ISO-IMAGES/$release/$image.xz
    fetch $url
    ;;

*)
    printf "Sorry, $(auto-ostype) is not yet supported.\n"
    exit 1
    ;;

esac
