#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2016-04-13  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 \n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

case `auto-ostype` in
FreeBSD)
    cat << EOM

Notes:

Users must be in the operator group to access USB ports and other
hardware.

Users must be in the wheel group in order to "su" to root.

EOM
    adduser
    ;;
*)
    printf "$0: `auto-ostype` is not yet supported.\n"
    exit 1
    ;;
esac

