#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2016-01-05  root        Begin
##########################################################################

usage()
{
    printf "Usage: $0 prefix license\n\nEx. $0 /usr/pkg-1 acm-license\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

prefix=$1
license=$2
auto-append-line $license "ACCEPTABLE_LICENSES+=\t$license" $prefix/etc/mk.conf $0

