#!/bin/sh -e

case $(auto-ostype) in
FreeBSD)
    : ${PORTSDIR:=/usr/ports}
    pkg install -y fusefs-ntfs fusefs-ext2 \
	fusefs-hfsfuse fusefs-lkl fusefs-simple-mtpfs zenity autoconf automake
    if ! auto-package-installed sysutils/fusefs-exfat; then
	(cd $PORTSDIR/sysutils/fusefs-exfat && make install clean)
    fi
    if ! auto-package-installed sysutils/exfat-utils; then
	(cd $PORTSDIR/sysutils/exfat-utils && make install clean)
    fi
    
    sysrc kld_list+=fuse
    
    am=/etc/auto_master
    sed -i '' -e 's|#.*/media|/media|' $am
    if ! grep -q '^/media.*,sync' $am; then
	sed -i '' -e '/^\/media/s|$|,sync|' $am
    fi
    auto-append-line 'autofs_enable="YES"' /etc/rc.conf $0
    auto-append-line 'autounmountd_flags="-r 5 -t 5"' /etc/rc.conf $0
    for service in automount automountd autounmountd devd; do
	service $service restart
    done
    
    cat << EOM

Autounmountd is set to check every 5 seconds.  Adjust in /etc/rc.conf
if desired.

EOM
    ;;

*)
    printf "$0: Not supported on $(auto-ostype).\n"
    ;;

esac
