#!/bin/sh

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-01-21  Jason Bacon Begin
##########################################################################

##########################################################################
#   Function description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2013-01-21  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 category/${port_or_package} variable-name\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if which bmake > /dev/null 2>&1; then
    make=bmake
    port_or_package=package
    base_dir=/usr/pkgsrc
else
    make=make
    port_or_package=port
    base_dir=/usr/ports
fi

case $# in
2)
    ;;
4)
    if [ $1 = '-p' ]; then
	base_dir=$2
	shift
	shift
    else
	usage
    fi
    ;;
*)
    usage
    ;;
esac

if [ ! -d $base_dir/$1 ]; then
    printf "No such ${port_or_package}: $base_dir/$1\n"
    exit 2
fi

makefile=/tmp/pkgname.$$
cat << EOM > $makefile

# Prevent HAVE_GNOME from adding -gnome to PKGNAME
WITHOUT_GNOME=  yes

print-variable:
	@echo \${$2}

.include "$base_dir/$1/Makefile"
EOM

# cat $makefile
cd $base_dir/$1
# bmake echoes pwd, so filter it out
${make} -f $makefile print-variable | fgrep -v $base_dir
rm -f $makefile

