#!/bin/sh -e

##########################################################################
#   Synopsis:
#       auto-chromium+widevine-install
#       
#   Description:
#       .B auto-chromium+widevine-install
#       automatically configures the system for widevine DRM
#       compatibility and installs the widevine plugin and chromium
#       browser with widevine enabled.
#       
#   Arguments:
#       None
#       
#   Returns:
#       0 on success, non-zero error codes otherwise
#
#   See also:
#       auto-install-linux_base
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 64     # sysexits(3) EX_USAGE
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

case $(auto-ostype) in
FreeBSD)
    linux_base=rl9
    if ! df | grep /compat/linux/dev; then
	auto-install-linux_base $linux_base
    fi
    
    if ! pkg info --exists linux-widevine-cdm; then
	cd /usr/ports/www/linux-widevine-cdm
	make clean install
    fi
    
    pkg install -y foreign-cdm chromium
    ;;

*)
    auto-unsupported-os $0
    exit 1
    ;;

esac    
