#!/bin/sh -e

##########################################################################
#   Title:
#       Optional, defaults to the name of the script sans extention
#
#   Section:
#       8
#
#   Synopsis:
#       
#   Description:
#       
#   Arguments:
#       
#   Returns:
#
#   Examples:
#
#   Files:
#
#   Environment:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2024-11-11  Jason Bacon Add man page template and usage
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}

##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi
    
case $(auto-ostype) in
FreeBSD)
    # Required by bash
    auto-append-line /proc 'proc\t\t/proc\t\t\tprocfs\trw\t\t0\t0' /etc/fstab $0
    if ! mount | fgrep -qw procfs; then
	mount proc
    fi
    ;;
    
*)
    auto-unsupported-os $0
    exit 1
    ;;

esac
