#!/bin/sh -e

case $(auto-ostype) in
FreeBSD)
    auto-fusefs-install
    pkg install -y automount npmount qmediamanager
    cat << EOM > /usr/local/etc/automount.conf
FM=/usr/local/bin/qmediamanager
MNT_GROUP=operator
MNT_MODE=775
EOM
    service devd restart
    ;;

NetBSD)
    auto-fusefs-install
    pkgin install -y automount npmount qmediamanager || true
    cat << EOM > $(auto-pkgsrc-prefix)/etc/automount.conf
FM=$(auto-pkgsrc-prefix)/bin/qmediamanager
MNT_GROUP=operator
MNT_MODE=775
EOM
    service devd restart
    ;;

*)
    auto-unsupported-os $0
    exit 1
    ;;

esac
