#!/bin/sh -e

##########################################################################
#   Synopsis:
#       auto-webcamd-setup
#
#   Description:
#       Install and configure software needed for webcams.  Also
#       prompts to enable individual users.
#
#   Arguments:
#       None.
#
#   Returns:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2022-07-12  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi
	
case $(auto-ostype) in
FreeBSD)
    # https://www.davidschlachter.com/misc/freebsd-webcam-browser
    LOADER_CONF=/boot/loader.conf
    RC_COND=/etc/rc.conf
    pkg install -y webcamd pwcview v4l-utils v4l_compat
    kldload cuse || true
    auto-set-conf-var cuse_load '"YES"' $LOADER_CONF $0
    auto-enable-service webcamd $0
    dmesg | grep ^ugen | tail
    while [ -z "$ugen" ]; do
	printf "Enter the ugen number shown above for your camera.\n"
	read -p "ugen device? (e.g. 1.5) " ugen
    done
    sysrc webcamd_0_flags="-d ugen$ugen"
    service devd restart
    service webcamd restart
    user_name='x'
    while [ -n "$user_name" ]; do
	read -p 'Username to use webcam? (Press Enter to skip) ' user_name
	if [ -n "$user_name" ]; then
	    pw groupmod webcamd -m $user_name
	fi
    done
    printf "Run pwcview -d /dev/video0 to test.\n"
    ;;

*)
    # FIXME: Make auto-unsupported-os return 1?
    auto-unsupported-os $0
    exit 1
    ;;

esac
