#!/bin/sh

##########################################################################
#   Title:
#       Optional, defaults to the name of the script sans extention
#
#   Section:
#       8
#
#   Synopsis:
#       
#   Description:
#       
#   Arguments:
#       
#   Returns:
#
#   Examples:
#
#   Files:
#
#   Environment:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2024-11-11  Jason Bacon Add man page template and usage
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

# Prevent discovery of last boot time
case $(auto-ostype) in
FreeBSD)
    auto-set-sysctl net.inet.tcp.rfc1323 0 $0
    ;;

RHEL)
    auto-set-sysctl net.ipv4.tcp_timestamps 0 $0
    ;;

*)
    auto-unsupported-os $0
    exit 1
    ;;

esac
