#!/bin/sh -e

##########################################################################
#   Title:
#       Optional, defaults to the name of the script sans extention
#
#   Section:
#       8
#
#   Synopsis:
#       
#   Description:
#       Display ASCII art banner
#       https://www.ascii-art-generator.org/
#       Font type: Slant
#       
#   Arguments:
#       
#   Returns:
#
#   Examples:
#
#   Files:
#
#   Environment:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2020-12-21  Jason Bacon Begin
#   2024-11-11  Jason Bacon Add man page template and usage
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}

##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

cat << EOM
	       ___         __           ___       __          _     
	      /   | __  __/ /_____     /   | ____/ /___ ___  (_)___ 
	     / /| |/ / / / __/ __ \   / /| |/ __  / __ \`__ \/ / __ \\
	    / ___ / /_/ / /_/ /_/ /  / ___ / /_/ / / / / / / / / / /
	   /_/  |_\__,_/\__/\____/  /_/  |_\__,_/_/ /_/ /_/_/_/ /_/ 
	   _________________________________________________________
		  
		  Portable Command-line Systems Management
		      https://acadix.biz/auto-admin.php
	   _________________________________________________________
EOM
