#!/bin/sh -e

##########################################################################
#   Title:
#       Optional, defaults to the name of the script sans extention
#
#   Section:
#       8
#
#   Synopsis:
#       
#   Description:
#       Set up linux_base on a FreeBSD system
#       
#   Arguments:
#       
#   Returns:
#
#   Examples:
#
#   Files:
#
#   Environment:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2018-08-27  J Bacon     Begin
#   2024-11-12  Jason Bacon Add man page template and usage
##########################################################################

usage()
{
    printf "Usage:\n\n" >> /dev/stderr
    for base in $(ls -d $PORTSDIR/emulators/linux_base*); do
	printf "$0 ${base##*-}\n" >> /dev/stderr
    done
    exit 1
}


##########################################################################
#   Main
##########################################################################

: ${PORTSDIR:=/usr/ports}

case $# in
1)
    linux_base=$1
    ;;

*)
    usage
    ;;

esac
if [ ! -e /usr/ports/emulators/linux_base-$linux_base ]; then
    printf "No such linux_base: linux_base-$linux_base\n" >> /dev/stderr
    exit 1
fi

export AUTO_ASK_TAG_PREFIX=auto-install-linux_base
    
case $(auto-ostype) in
FreeBSD)
    # FIXME: Support $PORTSDIR
    MAKE_CONF=/etc/make.conf
    major=`uname -r | cut -d '.' -f 1`
    
    # Install linux_base.  Can use 64-bit for 10.3 and later.
    major=`uname -r | cut -d . -f 1`
    minor=`uname -r | cut -d . -f 2 | cut -d - -f 1`
    if [ `uname -m` = amd64 ]; then
	linux64=y
    else
	linux64=n
    fi
    pkg delete -f -y linux_base\* || true
    if [ $linux64 = y ]; then
	#auto-append-line OVERRIDE_LINUX_BASE_PORT=$linux_base_64 $MAKE_CONF $0
	#auto-append-line OVERRIDE_LINUX_NONBASE_PORTS=$linux_base_64 $MAKE_CONF $0
	#auto-append-line DEFAULT_VERSIONS+=linux=$linux_base_64 $MAKE_CONF $0
	kldload linux || true
	kldload linux64 || true
    else
	touch $MAKE_CONF    # Prevent no such file error below
	#sed -i '.bak' -e 's|OVERRIDE_LINUX_BASE_PORT=$linux_base_64||' $MAKE_CONF
	#sed -i '.bak' -e 's|OVERRIDE_LINUX_NONBASE_PORTS=$linux_base_64||' $MAKE_CONF
	#sed -i '.bak' -e '/DEFAULT_VERSIONS+=linux=$linux_base_64/d' $MAKE_CONF
	kldload linux || true
    fi
    pkg install -y linux_base-$linux_base
    
    # FIXME: Use auto-set-conf-var
    auto-append-line 'linux_enable="YES"' /etc/rc.conf $0
    
    auto-append-line linprocfs "linprocfs\t/compat/linux/proc\tlinprocfs\trw\t0\t0" /etc/fstab $0
    if ! df | fgrep -q /compat/linux/proc; then
	mount /compat/linux/proc
    fi
    
    auto-append-line /compat/linux/dev/shm "tmpfs\t\t/compat/linux/dev/shm\ttmpfs\trw,mode=1777\t0\t0" /etc/fstab $0
    if ! df | fgrep /compat/linux/dev/shm; then
	mount /compat/linux/dev/shm
    fi
    
    auto-append-line linsysfs "linsysfs\t/compat/linux/sys\tlinsysfs\trw\t0\t0" /etc/fstab $0
    if ! df | fgrep -q /compat/linux/sys; then
	mount /compat/linux/sys
    fi
    ;;
    
*)
    auto-unsupported-os $0
    exit 1
    ;;

esac
