#!/bin/sh -e

##########################################################################
#   Script description:
#       Remove a user from a group
#
#   Arguments:
#       user-name
#       group-name
#       
#   History:
#   Date        Name        Modification
#   2019-10-09  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 user-name group-name\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

user_name=$1
group_name=$2

case $(auto-ostype) in
DragonFly|FreeBSD)
    pw groupmod $group_name -d $user_name
    ;;

NetBSD|OpenBSD)
    printf "$(auto-ostype) lacks a command for removing a user from a group.\n"
    printf "Edit /etc/group manually.\n"
    ;;

RHEL)
    # Cannot be done conveniently with usermod
    gpasswd -d $user_name $group_name
    ;;

*)
    auto-unsupported-os $0
    exit 1
    ;;

esac
