#!/bin/sh -e

##########################################################################
#   Title:
#       Optional, defaults to the name of the script sans extention
#
#   Section:
#       8
#
#   Synopsis:
#       
#   Description:
#       
#   Arguments:
#       
#   Returns:
#
#   Examples:
#
#   Files:
#
#   Environment:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2024-09-23  Jason Bacon Add man page template and usage
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

case $(auto-ostype) in
FreeBSD)
    # Required by bash
    auto-append-line /dev/fd 'fdesc\t\t/dev/fd\t\t\tfdescfs\trw\t\t0\t0' /etc/fstab $0
    if ! mount | fgrep -qw fdescfs; then
	mount fdesc
    fi
    ;;
    
*)
    auto-unsupported-os $0
    exit 1
    ;;

esac
