#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

cat << EOM

Warning: $0 is deprecated.
Please use auto-ports-wip-checkout.

EOM
pause
auto-ports-wip-checkout
