#!/bin/sh -e

##########################################################################
#   Script description:
#       Add a user to a group
#
#   Arguments:
#       user-name
#       group-name
#       
#   History:
#   Date        Name        Modification
#   2018-11-09  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 user-name group-name\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

user_name=$1
group_name=$2

case $(auto-ostype) in
FreeBSD)
    pw groupmod $group_name -m $user_name
    ;;

NetBSD)
    usermod -G $group_name $user_name
    ;;
    
RHEL)
    usermod -a -G $group_name $user_name
    ;;

Darwin)
    dseditgroup -o edit -a $user_name -t user $group_name
    ;;

*)
    auto-unsupported-os $0
    exit 1
    ;;

esac
