#!/bin/sh -e

##########################################################################
#   Script description:
#       Check current status of an account
#
#   Arguments:
#       Optional username, defaults to self
#       
#   History:
#   Date        Name        Modification
#   2018-11-08  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 \n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

case $# in
0)
    user_name=$(whoami)
    ;;
1)
    user_name=$1
    ;;
*)
    usage
    ;;
esac

case $(auto-ostype) in
FreeBSD)
    user_name=$1
    if awk -F : -v user_name=$user_name '$1 == user_name { print $2 }' /etc/master.passwd | grep -q '^*LOCKED*'; then
	printf "$user_name (locked)\n"
    else
	printf "$user_name (active)\n"
    fi
    ;;

RHEL)
    passwd --status $user_name
    ;;

*)
    auto-unsupported-os $0
    exit 1
    ;;

esac
