#!/bin/sh -e

##########################################################################
#   Title:
#       Optional, defaults to the name of the script sans extention
#
#   Name:
#       script - short description
#
#   Section:
#       8
#
#   Synopsis:
#       
#   Description:
#       
#   Arguments:
#       
#   Returns:
#
#   Examples:
#
#   Files:
#
#   Environment:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2024-09-23  Jason Bacon Add man page template and usage
##########################################################################

usage()
{
    printf "Usage: $0 [days-old: default=180]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

case $# in
1)
    days=$1
    ;;
0)
    days=180
    ;;
*)
    usage
    ;;
esac

for dir in /tmp /var/tmp /usr/tmp; do
    if [ -d $dir ]; then
	find $dir -depth -type f -atime +$days -print -exec rm -f '{}' \;
    fi
done
