#!/bin/sh -e

##########################################################################
#   Title:
#       Optional, defaults to the name of the script sans extention
#
#   Name:
#       script - short description
#
#   Section:
#       8
#
#   Synopsis:
#       
#   Description:
#       Disable file transfer commands.
#       Useful on cluster head nodes.
#       
#   Arguments:
#       
#   Returns:
#
#   Examples:
#
#   Files:
#
#   Environment:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2024-09-23  Jason Bacon Add man page template and usage
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

case $(auto-ostype) in
RHEL)
    chmod o-rwx /usr/bin/scp /usr/bin/sftp /usr/bin/rsync
    ;;
    
*)
    auto-unsupported-os $0
    exit 1
    ;;

esac
