#!/bin/sh

if [ $# != 1 ]; then
    printf "Usage: $0 rc.conf-name\n"
    exit 1
fi

service=$1
if auto-service-enabled $service; then
    sed -I '.bak' -e "s|${service}_enable=\"YES\"|${service}_enable=\"NO\"|g" \
	/etc/rc.conf
fi

