#!/bin/sh

# Check usage

# Alternative PORTSDIR?

PORTSDIR='/usr/ports'
makefile=${PORTSDIR}/$1/Makefile

if [ ! -e ${PORTSDIR}/$1 ]; then
    exit 1
fi

basename=`echo $1 | awk -F '/' ' { print $2 }'`

# bsd.mk.conf:
# PKGVERSION=     ${PORTVERSION:C/[-_,]/./g}${_SUF1}${_SUF2}

# R-cran ports may use DISTVERSION= x.y_z.  Convert to x.y.z.
first=`echo $basename | awk -F '-' ' { print $1 }'`
second=`echo $basename | awk -F '-' ' { print $2 }'`
name=`awk '$1 ~ "^PORTNAME.?=" { print $2 }' $makefile`
# printf "name = %s\n" $name
if [ x$first = xR ] && [ x$second = xcran ]; then
    name='R-cran-'$name
fi
if [ x$name = x ]; then
    # Get name from master
    if fgrep -q 'MASTERDIR=' $makefile; then
	masterdir=`awk '$1 ~ "^MASTERDIR.?=" { print $2 }' $makefile`
	masterdir=${masterdir#\$\{.CURDIR\}/}
	name=`awk '$1 ~ "^PORTNAME.?=" { print $2 }' ${PORTSDIR}/$1/$masterdir/Makefile`
    fi
fi
# Check for PKGNAMESUFFIX and FFTW*_FLAVOR
suffix=`awk '$1 ~ "^PKGNAMESUFFIX.?=" { print $2 }' $makefile`
# FIXME: This hack ignores variables used to set PKGNAMESUFFIX
# Works for fftw, where the variable is empty unless set by a slave port
if [ x`echo $suffix | cut -c 1` != x'$' ]; then
    name=${name}${suffix}
fi

prefix=`awk '$1 ~ "^PKGNAMEPREFIX.?=" { print $2 }' $makefile`
name=${prefix}${name}

flavor=`awk '$1 ~ "_FLAVOR.?=" { print $2 }' $makefile`
if [ x$flavor != x ]; then
    name=${name}-${flavor}
fi

version=`awk '$1 ~ "^PORTVERSION.?=" { print $2 }' $makefile`
if [ x$version = x ]; then
    if [ x$first = xR ] && [ x$second = xcran ]; then
	version=`awk '$1 ~ "^DISTVERSION.?=" { print $2 }' $makefile| tr '-' '.'`
    fi
    
    # Slave ports get version from master
    if fgrep -q 'MASTERDIR=' $makefile; then
	masterdir=`awk '$1 ~ "^MASTERDIR.?=" { print $2 }' $makefile`
	masterdir=${masterdir#\$\{.CURDIR\}/}
	version=`awk '$1 ~ "^PORTVERSION.?=" { print $2 }' ${PORTSDIR}/$1/$masterdir/Makefile`
    fi
fi

revision=`awk '$1 ~ "^PORTREVISION.?=" { print $2 }' $makefile`
if [ x$revision = x ]; then
    # Get name from master
    if fgrep -q 'MASTERDIR=' $makefile; then
	masterdir=`awk '$1 ~ "^MASTERDIR.?=" { print $2 }' $makefile`
	masterdir=${masterdir#\$\{.CURDIR\}/}
	revision=`awk '$1 ~ "^PORTREVISION.?=" { print $2 }' ${PORTSDIR}/$1/$masterdir/Makefile`
    fi
fi

epoch=`awk '$1 ~ "^PORTEPOCH.?=" { print $2 }' $makefile`
if [ x$epoch = x ]; then
    # Get name from master
    if fgrep -q 'MASTERDIR=' $makefile; then
	masterdir=`awk '$1 ~ "^MASTERDIR.?=" { print $2 }' $makefile`
	masterdir=${masterdir#\$\{.CURDIR\}/}
	epoch=`awk '$1 ~ "^PORTEPOCH.?=" { print $2 }' ${PORTSDIR}/$1/$masterdir/Makefile`
    fi
fi


db_dir="/var/db/pkg/$name-$version"
if [ x$revision != x ]; then
    db_dir=${db_dir}_$revision
fi
if [ x$epoch != x ]; then
    db_dir=${db_dir},$epoch
fi
printf "$db_dir\n"

