#!/bin/sh -e

##########################################################################
#   Script description:
#       Set up linux_base on a FreeBSD system
#
#   History:
#   Date        Name        Modification
#   2018-08-27  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0 6|7\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

# FIXME: Support $PORTSDIR
MAKE_CONF=/etc/make.conf
centos_version=$1
major=`uname -r | cut -d '.' -f 1`
# Let flash port install the default linux_base as a depend

# Install linux_base.  Can use 64-bit for 10.3 and later.
linux_base=c$centos_version
major=`uname -r | cut -d . -f 1`
minor=`uname -r | cut -d . -f 2 | cut -d - -f 1`
if [ `uname -m` = amd64 ]; then
    linux64=`auto-ask linux64 'Use 64-bit Linux compatibility? (y/n)' y`
else
    linux64=n
fi
pkg delete -f -y linux_base\* || true
if [ $linux64 = y ]; then
    #auto-append-line OVERRIDE_LINUX_BASE_PORT=c${centos_version}_64 $MAKE_CONF $0
    #auto-append-line OVERRIDE_LINUX_NONBASE_PORTS=c${centos_version}_64 $MAKE_CONF $0
    auto-append-line DEFAULT_VERSIONS+=linux=c${centos_version}_64 $MAKE_CONF $0
    kldload linux || true
    kldload linux64 || true
else
    touch $MAKE_CONF    # Prevent no such file error below
    #sed -i '.bak' -e 's|OVERRIDE_LINUX_BASE_PORT=c${centos_version}_64||' $MAKE_CONF
    #sed -i '.bak' -e 's|OVERRIDE_LINUX_NONBASE_PORTS=c${centos_version}_64||' $MAKE_CONF
    sed -i '.bak' -e '/DEFAULT_VERSIONS+=linux=c${centos_version}_64/d' $MAKE_CONF
    kldload linux || true
fi
cd /usr/ports/emulators/linux_base-$linux_base
make clean reinstall
