#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2012-01-08  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 [-c] category/port\n"
    exit 1
}
    

##########################################################################
#   Main
##########################################################################

case $# in
1)
    create=0
    ;;
2)
    if [ $1 != '-c' ]; then
	usage
    fi
    create=1
    shift
    ;;
*)
    usage
    ;;
esac

category=`dirname $1`
portname=`basename $1`
if [ $category = "." ]; then
    usage
fi

if [ ! -e /usr/ports/$category/$portname ] && [ $create != 1 ]; then
    printf "$category/$portname: No such port.\n"
    exit 1
fi

cd /usr/ports/$category
if [ -d $portname/.svn ]; then
    cd $portname && svn up
else
    if [ -e $portname ]; then
	mv $portname $portname.old.`date '+%Y.%m.%d.%H.%M.%S'`
    fi
    svn checkout https://svn0.us-east.FreeBSD.org/ports/head/$category/$portname $portname
fi

