#!/bin/sh

# Required by bash
auto-append-line /compat/linux/proc 'linproc\t\t/compat/linux/proc\t\t\tlinprocfs\trw\t\t0\t0' /etc/fstab $0
if ! mount | fgrep -qw linprocfs; then
    mount linproc
fi

