#!/bin/sh

cat << EOM

The amd service has been deprecated and replaced by autofs.

Please use auto-autofs-nfs-setup instead.

EOM

printf 'Are you sure you want to continue? y/[n] '
read continue
if [ 0$continue != 0y ]; then
    exit
fi

rc_file='/etc/rc.conf'
map_file='/etc/amd.map'

auto-enable-service -s statd rpc_statd $0
auto-enable-service -s lockd rpc_lockd $0

service lockd restart
service statd restart

# Add amd_enable="YES" to rc.conf
if ! fgrep -wq 'amd_enable="YES"' $rc_file; then
    printf "# Added by amd_setup\n" >> $rc_file
    printf 'amd_enable="YES"\n' >> $rc_file
else
    printf "AMD already enabled.\n"
fi

# Add entry to $map_file
# sculpin         type:=nfs;rhost:=sculpin;rfs:=/usr
printf "Mount point under /net? "
read mount_point
printf "Server hostname or IP? "
read server_name
printf "Exported directory on server? "
read server_export

line=`awk '$1 == "'$mount_point'"' $map_file`
if [ x"$line" = x'' ]; then
    printf "$mount_point\t\ttype:=nfs;rhost:=$server_name;rfs:=$server_export\n" \
	>> $map_file
    # Restart amd service
    /etc/rc.d/amd restart
else
    printf "$mount_point already exists in amd.map.\n"
fi

printf "Updating /etc/rc.resume...\n"
if ! fgrep -q '/etc/rc.d/amd' /etc/rc.resume; then
    sed -i 'orig' -E 's|exit 0|# Added by desktop-installer \
/etc/rc.d/amd restart \
\
exit 0|g' /etc/rc.resume
fi

printf "FreeBSD 7.2, 7.3, and 8.0 users should consult security advisory\n"
printf "FreeBSD-SA-10:06.nfsclient.\n"
