#!/bin/sh -e

if [ $# != 1 ]; then
    printf "Usage: $0 rc.conf-name\n"
    exit 1
fi
    
case $(auto-ostype) in
FreeBSD)
    service=$1
    fgrep -q "${service}_enable=\"YES\"" /etc/rc.conf
    exit $?
    ;;
    
*)
    printf "$0: Not supported on $(auto-ostype).\n"
    exit 1
    ;;

esac
