#!/bin/sh -e

##########################################################################
#   Synopsis:
#       auto-add-swap path-to-swapfile size (mibibytes)
#
#   Description:
#       The auto-add-swap script creates a swap file, activates it, and
#       configures the system to automatically activate it at boot time.
#       The new swap file serves as additional swap space if a swap
#       partition is already present.
#       
#   Arguments:
#       path-to-swapfile    Full pathname of the new swap file
#       size                Size of swap file in mibibytes
#       
#   Examples:
#       auto-add-swap /swapfile 4096
#
#   Returns:
#       0 on success, non-zero on failure
#
#   Files:
#       /etc/rc.conf (FreeBSD)
#
#   See also:
#       swapon(1), mdconfig(1) (FreeBSD)
#       
#   History:
#   Date        Name        Modification
#   2021-12-20  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 swap-file-path megabytes\n"
    printf "Example: $0 /swapfile 4096\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 2 ]; then
    usage
fi

swapfile=$1
mbytes=$2

case $(auto-ostype) in
FreeBSD)
    dir=$(dirname $swapfile)
    fs_type=$(df -T $dir | fgrep -v Filesystem | awk '{ print $2 }')
    if [ $fs_type = zfsx ]; then
	printf "Swap file on ZFS is currently not supported.\n"
	printf "Please choose another location.\n"
	exit 1
	# Not certain if ZFS swap is stable yet
	#pool=$(df -T $dir | fgrep -v Filesystem | awk '{ split($1, a, "/"); print a[1]; }')
	#sbase=$(basename $swapfile)
	#zfs create -V ${mbytes}M -o org.freebsd:swap=on -o checksum=off \
	#    -o compression=off -o dedup=off -o sync=disabled \
	#    -o primarycache=none $pool/$sbase
	#service zvol restart
    else
	if grep -q '^swapfile=' /etc/rc.conf; then
	    printf "Error: swapfile is already configured in rc.conf.\n"
	    exit 1
	else
	    # FIXME: Probably won't work with ZFS
	    dd if=/dev/zero of=$swapfile bs=1024k count=$mbytes
	    chmod 600 $swapfile
	    printf "swapfile=\"$swapfile\"" >> /etc/rc.conf
	    mdconfig -a -t vnode -f $swapfile -u 0 && swapon /dev/md0
	fi
    fi
    ;;

*)
    auto-unsupported-os $0
    exit
    ;;

esac
swapinfo
