#!/bin/sh -e
    
case $(auto-ostype) in
FreeBSD)
    # Required by bash
    auto-append-line /proc 'proc\t\t/proc\t\t\tprocfs\trw\t\t0\t0' /etc/fstab $0
    if ! mount | fgrep -qw procfs; then
	mount proc
    fi
    ;;
    
*)
    auto-unsupported-os $0
    exit 1
    ;;

esac
