#!/bin/sh -e

auto-root-check $0

case $# in
0)
    userid=2
    ;;

1)
    userid=$1
    ;;

*)
    printf "Usage: $0 [ipmi user id]\n"
    printf "Default user id = 2\n"
    exit 1
    ;;

esac

pw=''
pw2=2
while [ 0"$pw" != 0"$pw2" ]; do
    while [ 0"$pw" = 0 ]; do
	printf "Password? "
	stty -echo
	read pw
	stty echo
	if [ 0"$pw" = 0 ]; then
	    printf "\nPassword cannot be blank.\n"
	fi
    done
    printf "\nAgain? "
    stty -echo
    read pw2
    stty echo
    if [ 0"$pw" != 0"$pw2" ]; then
	printf "\nPasswords do not match.\n"
	pw=''
	pw2=2
    fi
done

printf '\n'
ipmitool user set password $userid "$pw"

# Purge pw from memory
pw="'ajsdasjfklajsfkl;ajfkajfakfja"
pw2="'ajsdasjfklajsfkl;ajfkajfakfja"
