#!/bin/sh -e

export AUTO_ASK_TAG_PREFIX=auto-install-linux-flash

case $(auto-ostype) in
FreeBSD)
    : ${LOCALBASE:=/usr/local}
    : ${PORTSDIR:=/usr/ports}

    # Speed up dependency installs
    pkg install -y pkgconf
    
    # Use www/flashplayer now.  Will install linux-flashplayer as dep
    flash=flashplayer
    
    if ! auto-package-installed www/$flash; then
	printf "Flash plugin may not install unless some vulnerable linux RPMs are allowed.\n"
	allow_vuln=`auto-ask vuln-flash 'Allow vulnerable linux RPMs? (y/n)' n`
	if [ $allow_vuln = y ]; then
	    linux_install_flags='DISABLE_VULNERABILITIES=1'
	fi

	# Check which linux_base flashplayer installs as a dep, then
	# run auto-install-linux_base to update fstab, etc.
	# Use -f to avoid recursively uninstalling important dependents
	# like nvidia-driver
	pkg remove -fy linux_base-c7 || true
	pkg remove -fy linux-flashplayer nspluginwrapper || true
	auto-install-linux_base 7
	
	# Must install from source to pull linux-flashplayer dep
	cd $PORTSDIR/www/$flash
	make -DBATCH $linux_install_flags clean deinstall reinstall
	
	rm -f $LOCALBASE/lib/firefox/plugins/libflash*
	rm -f $LOCALBASE/lib/firefox3/plugins/libflash*
	rm -f $LOCALBASE/lib/seamonkey/plugins/libflash*
    fi
    ;;

*)
    printf "$0: Not supported on $(auto-ostype).\n"
    exit 1
    ;;

esac
