#!/bin/sh -e

##########################################################################
#   Script description:
#       Mark a package to be rebuilt from source by auto-update-system
#       
#   History:
#   Date        Name        Modification
#   2021-01-13  Jason Bacon Begin
##########################################################################

usage()
{
    cat << EOM

Usage: $0 category/package reason

Marks a port for reinstalling from source by auto-update-system.  This
may be desirable to restore port options clobbered by "pkg upgrade",
upgrade ports that cannot be packaged, or build with optimized CFLAGS set
in /etc/make.conf.

The "reason" argument must not contain spaces.  It is a brief message that
will be displayed by auto-upgrade-system when rebuilding a package from
source.

Examples:

    $0 audio/lame license
    $0 math/openblas optimization
    $0 math/R build-options
    $0 wip/auto-admin work-in-progress

EOM
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -ne 2 ]; then
    usage
fi
pkg=$1
reason=$2

case $(auto-ostype) in
FreeBSD)
    : ${LOCALBASE:=/usr/local}
    mkdir -p $LOCALBASE/etc/auto-admin
    auto-append-line "$pkg $reason" \
	$LOCALBASE/etc/auto-admin/install-from-source nocomment
    ;;

*)
    # auto-pkgsrc-prefix exits non-zero if no tree found
    PKGSRC=$(auto-pkgsrc-prefix) || true
    if [ -z "$PKGSRC" ]; then
	printf "$0: No active pkgsrc tree found.\n"
	exit 1
    fi
    mkdir -p $PKGSRC/etc/auto-admin
    auto-append-line "$pkg $reason" \
	$PKGSRC/etc/auto-admin/install-from-source nocomment
    ;;

esac
