#!/bin/sh -e

##########################################################################
#   Script description:
#       Verify that calling user is a member of wheel.
#       
#   History:
#   Date        Name        Modification
#   2019-07-16  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 calling-script-name\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

if ! groups | fgrep -q wheel; then
    printf "$1 can only be run by members of wheel.\n"
    exit 1
fi
