#!/bin/sh -e

# Prompt for root password if needed
# su won't ask for pw if run as root
if [ $(whoami) != root ]; then
    printf "Root "
fi

case $(auto-ostype) in
FreeBSD)
    su -m root -c 'service netif restart && service routing restart'
    ;;

RHEL)
    # FIXME: Anything else?
    su -m root -c 'service network restart'
    ;;

*)
    printf "$0: Not supported on $(auto-ostype).\n"
    exit 1
    ;;

esac
