#!/bin/sh -e

case $(auto-ostype) in
FreeBSD)
    auto-fusefs-install

    for fm in caja; do
	if [ -e /usr/local/bin/$fm ]; then
	    chosen_fm=$fm
	    break
	fi
    done
    if [ 0$chosen_fm = 0 ]; then
	pkg install -y pcmanfm
	chosen_fm=/usr/local/bin/pcmanfm
    fi
    pkg install -y automount
    cat << EOM > /usr/local/etc/automount.conf
FM=$chosen_fm
MNT_GROUP=operator
MNT_MODE=775
EOM
    service devd restart
    ;;

*)
    printf "$0: Not supported on $(auto-ostype).\n"
    ;;

esac
