#!/bin/sh

# Prevent discovery of last boot time
case $(auto-ostype) in
FreeBSD)
    auto-set-sysctl net.inet.tcp.rfc1323 0 $0
    ;;

RHEL)
    auto-set-sysctl net.ipv4.tcp_timestamps 0 $0
    ;;

*)
    printf "$0: Not supported on $(auto-ostype).\n"
    exit 1
    ;;

esac

