#!/bin/sh -e

##########################################################################
#   Script description:
#       Mark a package critical for auto-update-system
#       
#   History:
#   Date        Name        Modification
#   2020-08-13  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 package [package ...]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    usage
fi

case $(auto-ostype) in
FreeBSD)
    : ${LOCALBASE:=/usr/local}
    mkdir -p $LOCALBASE/etc/auto-admin
    for pkg in "$@"; do
	auto-append-line $pkg $LOCALBASE/etc/auto-admin/critical-packages nocomment
    done
    port=$(pkg origin $pkg)
    if ! auto-package-installed $port; then
	exit 1
    fi
    ;;

*)
    # auto-pkgsrc-prefix exits non-zero if no tree found
    PKGSRC=$(auto-pkgsrc-prefix) || true
    if [ -z "$PKGSRC" ]; then
	printf "$0: No active pkgsrc tree found.\n"
	exit 1
    fi
    mkdir -p $PKGSRC/etc/auto-admin
    for pkg in "$@"; do
	auto-append-line $pkg $PKGSRC/etc/auto-admin/critical-packages nocomment
    done
    ;;

esac
