#!/bin/sh -e

case `auto-ostype` in
FreeBSD)
    pkg install -y ipmitool
    chmod 750 /usr/local/bin/ipmitool
    auto-append-line 'ipmi_load="YES"' /boot/loader.conf $0
    kldload ipmi
    ;;

RHEL)
    yum install -y OpenIPMI ipmitool
    chkconfig ipmi on
    service ipmi start
    chmod 750 /usr/bin/ipmitool
    ;;

*)
    auto-unsupported-os $0
    exit 1
    ;;

esac

