#!/bin/sh -e

if ! which dmidecode > /dev/null 2>&1; then
    printf "You must install dmidecode to use $0.\n"
    exit 1
fi

printf "BIOS:\n"
dmidecode -t bios | egrep 'Vendor|Version'

printf "\nSystem:\n"
dmidecode -t system | egrep 'Manufacturer|Product|Serial|UUID'

printf "\nBase board:\n"
dmidecode -t baseboard | egrep 'Manufacturer|Product|Version|Serial'

printf "\nCPUs:\n"
dmidecode -t processor | egrep 'Socket|Version|Speed|Core|Thread'

printf "\nMemory:\n"
dmidecode -t memory | egrep 'Capacity|Size|Locator|Type|Speed.*MT'

cat << EOM

Run dmidecode directly for more detailed information.

EOM
