#!/bin/sh -e

##########################################################################
#   Script description:
#       Print the release version of the underlying OS.
#       
#   History:
#   Date        Name        Modification
#   2016?       Jason Bacon Begin
##########################################################################

##########################################################################
#   Main
##########################################################################

if [ -e /etc/redhat-release ]; then
    release=`cat /etc/redhat-release`
    release=${release%%.*}
    release=${release##*release }
    os=RHEL$release
elif [ -e /etc/debian_version ]; then
    os=$(cat /etc/debian_version)
elif [ `uname` = Darwin ]; then
    os=$(uname)$(uname -r | cut -d . -f 1)
else
    os=$(uname)-$(uname -r)
fi
echo $os
