#!/bin/sh

case $(auto-os-release) in
FreeBSD*)
    # http://havokmon.blogspot.com/2012/07/proper-nfs-server-service-restart.html
    # killall -9 mountd
    # service nfsd stop
    # service rpcbind onestop
    # service rpcbind onestart
    # service nfsd start
    
    # Should suffice on modern FreeBSD
    service nfsd restart
    service mountd onereload
    if grep -q '^nfsuserd_enable="YES"' /etc/rc.conf; then
	service nfsuserd restart
    fi
    ;;

RHEL6)
    service nfs restart
    ;;

RHEL7|RHEL8)
    systemctl restart nfs
    ;;

*)
    printf "$0: Not supported on $(auto-os-release).\n"
    exit 1
    ;;

esac
