#!/bin/sh -e

##########################################################################
#   Script description:
#       Make sure ports branch matches pkg repo
#       
#   History:
#   Date        Name        Modification
#   2020-04-16  J Bacon     Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

case $(auto-ostype) in
FreeBSD)
    : ${PORTSDIR:=/usr/ports}
    export PORTSDIR
    
    if which svn > /dev/null; then
	svn=svn
    else
	svn=svnlite
    fi
    repo_branch=$(auto-pkg-branch)
    if [ ! -e $PORTSDIR/Makefile ]; then
	printf "No ports tree at $PORTSDIR.  Checking one out now...\n"
	auto-ports-checkout
    else
	# Generate name for backup ports dir in case we need it
	c=0
	while [ -e $PORTSDIR.$c ]; do
	    c=$((c + 1))
	done

	if ! auto-ports-branch; then
	    cat << EOM

Your ports tree is neither head nor quarterly and therefore cannot be
maintained by auto-update-system.  Moving to $PORTSDIR.$c and checking out
a new ports tree...
EOM
	    mv $PORTSDIR $PORTSDIR.$c
	    auto-ports-checkout
	    if [ -e $PORTSDIR.$c/wip ]; then
		mv $PORTSDIR.$c/wip $PORTSDIR
	    fi
	else
	    ports_branch=$(auto-ports-branch)
	    if [ $ports_branch != $repo_branch ]; then
		cat << EOM

Your binary packages are currently from the $repo_branch branch (or they
will be shortly when the new bulk builds complete).

$PORTSDIR is currently using the $ports_branch branch.

Software installed via $PORTSDIR will likely have version mismatches
with the $repo_branch binary packages.  To avoid this, you should replace
$PORTSDIR with the $repo_branch ports branch.

EOM
		printf "Replace $PORTSDIR with $repo_branch? (y/n) [y] "
		read correct
		if [ 0$correct != 0n ]; then
		    # FIXME: Add git support when appropriate
		    if [ -e $PORTSDIR/.svn ] && [ $repo_branch != latest ]; then
			printf "Switching svn repo to $repo_branch...\n"
			cd $PORTSDIR
			url=$($svn info | awk '$1 == "URL:" { print $2 }')
			new_url=$(echo $url | sed -e "s|ports/.*|ports/branches/$repo_branch|")
			$svn switch "$new_url"
		    else
			printf "Saving $PORTSDIR to $PORTSDIR.$c and checking out $repo_branch...\n"
			mv $PORTSDIR $PORTSDIR.$c
			# FIXME: Specify repo_branch
			auto-ports-checkout
	    		if [ -e $PORTSDIR.$c/wip ]; then
			    mv $PORTSDIR.$c/wip $PORTSDIR
	    		fi
		    fi
		fi
	    fi
	fi
    fi
    ;;

*)
    printf "$0: Not supported on $(auto-ostype).\n"
    exit 1
    ;;

esac
