#!/bin/sh

	# Check bwi before bwn.  They support the same devices, but
	# bwi seems to work better.
	for driver in an ath bwi bwn ipw iwi iwn malo mwl ral rum run uath upgt urtw wpi zyd; do
	    if kldload if_${driver} > /dev/null 2>&1; then
		printf "Loaded $driver.\n"
	    fi
	done
	
	wlan=0
	for driver in an ath bwi bwn ipw iwi iwn malo mwl ral rum run uath upgt urtw wpi zyd; do
	    if grep -q "^${driver}0" /var/run/dmesg.boot || \
		# FIXME: Check also for ${driver}1, ${driver}2, etc.
		# Also could use a better test than this simple grep.
		dmesg | grep -q "^${driver}0"; then
		printf "Found wireless device ${driver}0.\n"
		auto-append-line "wlans_${driver}0" "wlans_${driver}0=\"wlan$wlan\"" $RC_CONF desktop-installer
		# Not necessary for drivers which are in the GENERIC kernel, but
		# it shouldn't hurt.
		auto-append-line "if_${driver}_load=\"YES\"" \
		    "if_${driver}_load=\"YES\"" $LOADER_CONF desktop-installer
		wlan=$(($wlan + 1))
		# break   # Configure only one wireless device!
	    fi
	done
	auto-append-line 'ifconfig_wlan0' 'ifconfig_wlan0="WPA DHCP"' $RC_CONF desktop-installer

